project:
  type: website

website:
  site-url: "https://connect.strategyunitwm.nhs.uk/nhp/project_information"
  open-graph: true
  repo-url: https://github.com/The-Strategy-Unit/nhp_project_information
  repo-actions: [edit, issue]
  title: "NHP model project information"
  description: "Documentation for the Demand Model created by the Strategy Unit to support NHS England's New Hospital Programme"
  favicon: _assets/favicon.ico
  navbar:
    background: dark
    foreground: light
    title: "NHP model project information"
    pinned: true
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "Project overview"
        contents:
          auto: project_plan_and_summary/*
      - section: "User guide"
        contents:
          auto: user_guide/*
      - section: "Modelling methodology"
        contents:
          - modelling_methodology/methodology.qmd
          - modelling_methodology/demand_supply.qmd
          - modelling_methodology/need_supply.qmd
          - modelling_methodology/double_counting.qmd
          - modelling_methodology/modelling_uncertainty.qmd
          - modelling_methodology/non-demographic_growth.qmd
          - section: "Types of Potentially Mitigatable Activity (TPMAs)"
            contents:
              - modelling_methodology/activity_mitigators/inpatient_activity_mitigators.qmd
              - modelling_methodology/activity_mitigators/outpatient_activity_mitigators.qmd
              - modelling_methodology/activity_mitigators/ae_activity_mitigators.qmd
          - section: "Data quality"
            contents:
            - modelling_methodology/data_summary.qmd
            - modelling_methodology/baseline_data_validation.qmd
          - section: "Demographic modelling"
            contents:
              - auto: modelling_methodology/demographic_modelling/*.qmd
      - section: "Data extraction"
        contents:
          auto: data_extraction/*
      - section: "Quality assurance"
        contents:
          auto: quality_assurance/*
      - contact.qmd
  page-navigation: true
  page-footer:
    right: "[NHP Model Project Information](https://connect.strategyunitwm.nhs.uk/nhp/project_information/)© 2023 by [The Strategy Unit](https://www.strategyunitwm.nhs.uk/) is licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    left: "This page is built using the [NHS-R Quarto theme](https://github.com/nhs-r-community/quarto-nhs-theme)."

format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html

execute:
  freeze: false
  echo: false


callout-appearance: simple
