---
title: "Parsing model results files"
order: 8
---

Results from the model are viewable in the [NHP model outputs app](https://connect.strategyunitwm.nhs.uk/nhp/outputs/).
The outputs app provides a range of visualisations and summarisations of model results; however, users may wish to also conduct their own analysis based on the more detailed raw results file, which is available to download in [JSON format](https://en.wikipedia.org/wiki/JSON).
This page aims to explain the structure of the NHP model results JSON file. It reflects the structure of the results files from model v3.0.

The JSON results file has three keys:

- `params`  The full parameters that were used for the model run. This is the JSON that is created and submitted to the model from the inputs app.
- `population_variants`  An array of length equal to the number of Monte Carlo simulations. Lists the population variants that were utilised for each model run in the Monte Carlo simulations.
- `results`  The actual model results, a set of 7 key-value pairs.
    - `default`  An array containing the model results grouped by `sitetret`, `measure`, and `pod`. Shows the results of the `principal` model run and the `baseline` value. Also shows the results of each of the Monte Carlo simulations in `model_runs`, the `lwr_ci`, `median` and `upr_ci` values from the Monte Carlo simulation runs, and the estimated year-by-year growth from baseline year to horizon year using the [principal projection parameters](https://connect.strategyunitwm.nhs.uk/nhp/project_information/user_guide/glossary.html#principal-projection) in `time_profiles`.
    - `sex+age_group`  An array containing the model results as found in `default`, but also including breakdowns by `age_group` and `sex`. The age groups used are:
        - 0
        - 1-4
        - 5-9
        - 10-15
        - 16-17
        - 18-34
        - 35-49
        - 50-64
        - 65-74
        - 75-84
        - 85+
        - Unknown
    - `age` An array containing the model results as found in `default`, but also including breakdowns by the age, in integers.
    - `sex+tretspef`  An array containing the model results as found in `default`, but also including breakdowns by grouped `tretspef` and `sex`. The `tretspef` groupings can be [seen here](https://connect.strategyunitwm.nhs.uk/nhp/project_information/data_extraction/inpatients.html#tretspef).
    - `tretspef_raw+los_group`  An array containing the model results for inpatients as found in `default`, but also including breakdowns by `tretspef_raw` and `los_group`. The Length of Stay groupings are:
        - 0-day
        - 1-day
        - 2-day
        - 3-day
        - 4-7 days
        - 15-21 days
        - 22+ days
        - 8-14 days
    - `step_counts`  An array containing the estimated [impact of changes](https://connect.strategyunitwm.nhs.uk/nhp/project_information/user_guide/glossary.html#impact-of-changes) caused by each parameter, also known as the `change_factor`. The data here is used for the 'waterfall diagrams' in the outputs app. The impact of each change factor is broken down by `activity_type`, `pod`, `measure`, and `sitetret`. We also break down the mitigators by each specific `strategy`. We show the estimated impact of each change factor for every Monte Carlo simulation in the `model_runs` and the estimated year-by-year impact of each change factor from baseline year to horizon year in the `time_profiles`.
    - `tretspef_raw`  An array containing the model results for outpatients as found in `default`, but also including breakdowns by grouped `tretspef_raw`.