---
title: "Model inputs and outputs"
order: 2
---

## Inputs

There are two main types of inputs for the model:

### Data

-   Historical national hospital activity data: This will be sourced from Hospital Episode Statistics (HES) data, and will be the main source for input data. It provides record/person-level data on historical hospital activity.
-   ONS population and life expectancy projections: This may be supplemented by local/regional projections, such as housing growth estimates.
-   Other published data sets: This includes Referral to Treatment (RTT) data and lookup tables mapping CCGs, trusts, sites and local authorities. Note that some of these datasets (such as RTT data) will be used to provide contextual information for users setting model parameters, rather than directly driving the model engine and outputs.

For more detail on the data used in the project see the [data summary page](../modelling_methodology/data_summary.qmd).

### Model parameters

The model takes as its parameters estimations of activity - more detail is available in the [parameters section](../user_guide/setting_the_parameters.qmd). These parameters are informed by:

-   **Expert opinion and local knowledge**\
    For example, assumptions on the impact of specific activity avoidance strategies and interventions, sometimes also known as types of potentially mitigatable activity (TPMAs). These inputs will be set locally by each Trust's representatives, but will also be informed by the results of the [NHP National Elicitation Exercise (NEE)](https://github.com/The-Strategy-Unit/nhp_elicitation_tool), which gathered through Delphi/SHELF elicitation methods an expert consensus of possible activity mitigation on a national level.

    All inputs will be sense-checked and compared across Trusts where appropriate, with any anomalies requiring further evidence to support them.

-   **Secondary analysis, modelling and research**\
    Some of the inputs will be drawn directly from available literature and studies, but several inputs, such as the non-demographic growth values, are the product of subsidiary analysis and modelling.

The model will use the estimations of activity increase/decrease found in the parameters to transform the input data into estimations of future activity.

## Outputs

The model will generate the following key outputs for each scheme and set of scenarios:

-   A description of future hospital activity levels across a range of future years, based on the principal forecast from the tool. This will contain high-level summary statistics such as counts of admissions, outpatient attendances and bed days, along with more detailed information providing a breakdown by activity type, month, specialty, patient age, diagnosis, and so on.
-   A description of the potential variation in the high-level summary statistics given the uncertainty in the underpinning inputs, assumptions and estimates.
-   A summary of input assumptions and estimates, including how central estimates and probability distributions compare with those used in modelling for other local health systems participating in the NHP.
-   A detailed extract of the full model outputs, including record level data for each scenario/run of the Monte-Carlo simulation.

Note that some of these outputs, in particular record level data, will be restricted to the NHP Demand Modelling Team, whereas other high-level summary outputs will be shared more widely with key stakeholders.
