---
title: "Baseline data validation"
order: 3
---

As part of the self-directed learning process, we recommend that Trusts check the baseline counts of activity in the inputs app against their own locally held data. This will help to ensure that all stakeholders have confidence in the quality of the baseline data that forms the basis of the modelling process and will help to identify any issues that need to be addressed through the baseline adjustment, repatriation or expatriation model parameters. 

The baseline data can be downloaded as an Excel file from the inputs app, on the Baseline Adjustment page. 

The processing that is conducted to produce the NHP model baseline data counts is documented in the [data extraction section](../data_extraction/). 

We use HES data; further details on the fields in this dataset are available from the [HES Data Dictionary](https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/hospital-episode-statistics/hospital-episode-statistics-data-dictionary). 

If you have any queries, please contact the data science team by emailing [mlcsu.nhpanalytics@nhs.net](mailto:mlcsu.nhpanalytics@nhs.net). We can also supply the SQL code that is used to identify the activity affected by each mitigator, if required. 