---
title: "Coronavirus (COVID-19) Adjustment"
order: 4
---

Coronavirus (COVID-19) caused differing activity levels from what we would expect in a typical year. For the year 2019/20, most of the year was unaffected, but the final month (March 2020) saw a drastic reduction in the usual levels of activity.

In order to use 2019/20 as a baseline year, we need to oversample activity from the rest of the year. The methodology used is from the NHS England Operational Planning 2022/23 ICS Submission Activity and Performance Non Functional Template, v.09.

## Methodology

We group activity by type and group (see table below), and count how much activity happens per year and month.

| Inpatients   | Outpatients          | A&E       |
| :----------- | :------------------- | :-------- |
| Elective     | First Attendance     | Ambulance |
| Non-Elective | Follow-up Attendance | Walk-In   |
| Maternity    | Maternity            |           |

For the 3 years before 2019/20, we calculate the mean amount of activity per day in February and March, and take the ratio of March to February. We then calculate the mean of these ratios ($a$).

For 2019/20, we take the average amount of activity per day in February ($b$), then calculate the expected amount of activity in March ($c = a \times b \times 31$).

We can then take the difference between the $c$ and the actual amount of activity in March 2020, and we divide this by the total amount of activity in 2020. Finally, we add 1 to this value: this gives us the parameter for the Coronavirus (COVID-19) adjustment in the model, the amount to sample rows by from the baseline year.
