---
title: "Overview of components"
order: 1
---

Given the size of the project, there are numerous GitHub repositories relating to NHP, with this number likely to grow. This page gives an overview of the main repositories forming the backbone of the model. It is not exhaustive - if there are any queries on repositories not listed here, do contact a member of the Strategy Unit Data Science team.

# Repositories relating to model inputs

-   [nhp_demogr_module_inputs](https://github.com/The-Strategy-Unit/nhp_demogr_module_inputs)

This repository contains the code that specifies changes in the size, age/sex structure and health status of a hospital's catchment population. The code is written in R and makes use of data sources from the Office for National Statistics.

-   [nhp_strategies](https://github.com/The-Strategy-Unit/nhp_strategies)

This code is used to determine which healthcare activity belongs to a category that might be mitigated in the future, e.g. alcohol related admissions. The code is written in SQL and run in an R based [{targets}](https://cran.r-project.org/web/packages/targets/index.html) pipeline.

-   [nhp_inputs](https://github.com/The-Strategy-Unit/nhp_inputs)

This repository provides an interface for users to provide the parameters to feed into the model. It provides a variety of user-friendly functions such as saving inputs from previous runs and providing a document which summarises the parameters used in each run. This repository is written in R and implements a [Shiny](https://shiny.posit.co/) dashboard using [golem](https://thinkr-open.github.io/golem/).

# Repositories relating to the model run

-   [nhp_model](https://github.com/The-Strategy-Unit/nhp_model/)

    This repository contains the code that implements the methodologies to model future activity for hospitals. It takes all the input data, including the parameters set by users, and uses the monte carlo simulation method to produce estimates of future activity. This repository is written in Python.

# Repositories relating to model outputs

-   [nhp_outputs](https://github.com/The-Strategy-Unit/nhp_outputs)

This repository is a Shiny dashboard enabling exploration of the results of a single model run.

-   [nhp_comparer](https://github.com/The-Strategy-Unit/nhp_comparer)

This repository is a Streamlit dashboard enabling the comparison of the input parameters and results of two different model runs.

# Repositories relating to documentation

-   [nhp_documentation](https://github.com/The-Strategy-Unit/nhp_documentation)

This repository contains details of how activities which could be affected by activity mitigators are flagged when loading and processing the input data for each trust. It is built in Quarto and details the SQL and R code used.

-   [nhp_project_information](https://github.com/The-Strategy-Unit/nhp_project_information)

This is the repository hosting the content you are reading now. The aim is to provide a high level overview of the project as a whole.

# Open source policy

The policy of the Strategy Unit (MLCSU) and [national policy](https://www.gov.uk/government/publications/data-saves-lives-reshaping-health-and-social-care-with-data/data-saves-lives-reshaping-health-and-social-care-with-data#working-with-partners-to-develop-innovations-that-improve-health-and-care) both encourage sharing of code:

> ...new source code that we produce or commission open and reusable by default (with clear exceptions)

Source: [Data Saves Lives](https://www.gov.uk/government/publications/data-saves-lives-reshaping-health-and-social-care-with-data/data-saves-lives-reshaping-health-and-social-care-with-data#working-with-partners-to-develop-innovations-that-improve-health-and-care)

At the moment the codebase referred to in this documentation is closed, but we hope to make it open in the near future.
