---
title: "Assumptions Log"
---


The purpose of an assumptions log is to justify any decisions made about the data and methodologies used. 

Our assumptions log has the following columns

- ID: Unique reference for our assumptions
- Description: Short description of the assumption
- Methodolgy: Link to justification and evidence for the assumption
- Quality rating: Low, Medium or High
- ?Quality description: Reason for quality rating
- Impact rating: Low, Medium or High
- ?Impact description: Reason for impact rating
- Risk rating: Determined by quality rating and impact rating
- Actions: (Optional) Link to issue in the QA Plan

[Diagram of quality/impact risk mapping]()

This project website is version controlled and therefore historical versions of the assumption log can be found on [GitHub](https://github.com/The-Strategy-Unit/nhp_project_information).

<a href = "/modelling_methodology/covid_adjustment.qmd">example root link</a>

```{r}
assumptions <-
jsonlite::fromJSON("assumptions.json") |>
tibble::as_tibble() #|>
#dplyr::mutate(Methodology = glue::glue("<a href='{Methodology}'>Link</a>"))

# check_assumptions_log(file) # Asserts that the columns are correctly formatted and that the risk rating is correctly calculated

assumptions |>
reactable::reactable(
    columns = list(
    # Using htmltools to render a link
    Methodology = reactable::colDef(cell = function(value) {
      htmltools::tags$a(href = value, "Link")
    }, 
    `Impact rating` = colDef(cell = function(value) {
      class <- paste0("tag status-", tolower(value))
      div(class = class, value)
    })
    )
)
