---
title: Bed Capacity Conversion
---

The inpatients model generates activity based on admissions and number of days spent in a bed.
We use data from the [KH03][kh03] data returns along with the modelled and baseline activity to estimate the number of beds that may be required in the future.

[kh03]: https://www.england.nhs.uk/statistics/statistical-work-areas/bed-availability-and-occupancy/


$$
N=\cfrac{A_{future}}{A_{baseline}}\cdot\cfrac{B}{P}
$$

where:

- $A$ is the activity: the sum of length of stay (LoS) [LoS: difference between discharge date and admission date]{.aside}
- $B$ is the number of beds that were occupied in the baseline period, sourced from KH03.
- $P$ is the future occupancy rate paramater, provided by the user
- $N$ is the future amount of available beds

This calculation is performed by quarter, and by "ward group", which are definable in the model inputs by grouping main specialties together.

## Example

In the baseline, we may have 90 beds and a 90% occupancy rate (100 beds available).
We may want to target 80% occupancy in the future.

If in the baseline there were 100,000 bed nights, and in the future 120,000, with 90 beds in the baseline and a future occupancy rate of 90%, then we would get:

$$
N=\cfrac{120,000}{100,000}\cdot\cfrac{90}{0.8} = 1.2 \times 112.5 = 135
$$

## Data logic

We filter to only include patients who were `classpat == "1"` (ordinary admissions) with a `speldur > 0` (they spent at least 1 night in hospital).

We take the admission date, and we create a row from each data from the admission date (inclusive) to the discharge date (exclusive). For example if a patient was admitted on 01/01/2023 and discharged on 04/01/2023 (`speldur = 3`), then we would have the following rows:

- 01/01/2023
- 02/01/2023
- 03/01/2023

We then assign each of the rows to a quarter, then count in each quarter how many nights beds were occupied for by counting the number of rows in that quarter (per `mainspef`).