name: "Connect Publish (preview)"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  connect-publish:
    name: connect-publish-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Publish to RStudio Connect (and render)
        shell: bash
        env:
          QUARTO_PRINT_STACK: true
          CONNECT_SERVER: ${{ secrets.RSCONNECT_URL }}
          CONNECT_API_KEY: ${{ secrets.RSCONNECT_API_KEY }}
          AZ_STORAGE_ACCOUNT: ${{ secrets.AZ_STORAGE_ACCOUNT }}
          AZ_STORAGE_CONTAINER_SUPPORT: ${{ secrets.AZ_STORAGE_CONTAINER_SUPPORT }}
          AZ_STORAGE_CONTAINER_SUPPORT_SAS: ${{ secrets.AZ_STORAGE_CONTAINER_SUPPORT_SAS }}
        run: quarto publish --id a3a013e9-d405-46b7-a71e-1fae05a569f4 --no-browser

      - name: Publish to NEW RStudio Connect (and render)
        shell: bash
        env:
          QUARTO_PRINT_STACK: true
          CONNECT_SERVER: ${{ secrets.RSCONNECT_URL_NEW }}
          CONNECT_API_KEY: ${{ secrets.RSCONNECT_API_KEY_NEW }}
          AZ_STORAGE_ACCOUNT: ${{ secrets.AZ_STORAGE_ACCOUNT }}
          AZ_STORAGE_CONTAINER_SUPPORT: ${{ secrets.AZ_STORAGE_CONTAINER_SUPPORT }}
          AZ_STORAGE_CONTAINER_SUPPORT_SAS: ${{ secrets.AZ_STORAGE_CONTAINER_SUPPORT_SAS }}
        run: quarto publish --id 8a793bc6-6399-4260-b2c9-10fc040fda6f --no-browser
