name: "Connect Publish (dev)"
on:
  push:
    branches: [main]

jobs:
  connect-publish:
    name: connect-publish-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish to RStudio Connect (and render)
        shell: bash
        env:
          QUARTO_PRINT_STACK: true
          CONNECT_SERVER: ${{ secrets.RSCONNECT_URL }}
          CONNECT_API_KEY: ${{ secrets.RSCONNECT_API_KEY_NEW }}
        run: quarto publish --id 1feb633e-81c0-4a34-8a71-cc7338f03375 --no-browser
