name: "Connect Publish (preview)"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  connect-publish:
    name: connect-publish-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Publish to RStudio Connect (and render)
        shell: bash
        env:
          QUARTO_PRINT_STACK: true
          CONNECT_SERVER: ${{ secrets.RSCONNECT_URL }}
          CONNECT_API_KEY: ${{ secrets.RSCONNECT_API_KEY }}
          AZ_APP_ID: ${{ secrets.AZ_APP_ID }}
          AZ_APP_SECRET: ${{ secrets.AZ_APP_SECRET }}
          AZ_STORAGE_CONTAINER_SUPPORT: ${{ secrets.AZ_STORAGE_CONTAINER_SUPPORT }}
          AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
          AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
        run: |
          git config --global user.email "quarto-github-actions-publish@example.com"
          git config --global user.name "Quarto GHA Workflow Runner"

          quarto publish connect --id a3a013e9-d405-46b7-a71e-1fae05a569f4 --no-browser
